-- -- variables
-- local players = game:GetService("Players")

-- -- functions
-- local function onPlayerSpawn(player)
--     local leaderstats = Instance.new("Folder")
--     leaderstats.Name = "Leaderstats"
--     leaderstats.Parent = player

--     local coinCount = Instance.new("IntValue")
--     coinCount.Name = "CoinCount"
--     coinCount.Parent = leaderstats
--     coinCount.Value = 0
-- end    

-- -- executions
-- players.PlayerAdded:Connect(onPlayerSpawn)
